### ISSUE TITLE
Dropdown menu for connection type

### ISSUE THREAD

**Issue by SkymanOne** [SkyMen-Lab/AdminService#23]
### Problem
When the user tried to edit or create a config. The *connection type* field doesn't have options (drop-down menu), so you have to enter values (1 or 0) manually.

### Solution
Add drop-down element from Bootstrap to UI and couple it with Razor, so 0 stands for UDP and 1 for TCP

**Comment by N0ne1eft** [comment]
Fixed in https://github.com/SkyMen-Lab/AdminService/commit/e5db0e531b3a11926fc3c1a3ccdaac6588b1dbce
