### ISSUE TITLE
Redirect on a new page when team has been created

### ISSUE THREAD

**Issue by SkymanOne** [SkyMen-Lab/AdminService#6]
https://github.com/SkyMen-Lab/AdminService/blob/d35617a8b262807164df376eeb0c0b88f8375ee1/AdminService/Controllers/TeamController.cs#L45

When a school has been created, the user is better off seeing json response nicely rendered **on a new page** without inputs field as it confuses the user, because the input fields are not emptied

**Comment by N0ne1eft** [comment]
Added redirection to detail page https://github.com/SkyMen-Lab/AdminService/commit/983f201bd4b4feb8e41074c4fc0bf5269a6b150e

**Comment by N0ne1eft** [comment]
Added redirection for edit page as well https://github.com/SkyMen-Lab/AdminService/commit/2f866c1b292667b3947c3f4f2abdec742cccdf94
